export const SEND_REQUEST = 'SEND_REQUEST';
export const RESOLVE_REQUEST = 'RESOLVE_REQUEST';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const UNSET_NOTIFICATION = 'UNSET_NOTIFICATION';
export const SET_REDIRECT = 'SET_REDIRECT';
export const UPDATE_RETRY_COUNTER = 'UPDATE_RETRY_COUNTER';
export const IS_SHOW_APP_LOADER = 'IS_SHOW_APP_LOADER';