export const SET_SESSION = "SET_SESSION";
export const UNSET_SESSION = "UNSET_SESSION";
export const UPDATE_EMAIL = "UPDATE_EMAIL";
export const SET_AUTH_VERIFIED = "SET_AUTH_VERIFIED";
export const SET_REDIRECT = "SET_REDIRECT";
