<template lang="pug">
  v-container.py-0(
    fluid
  )
    v-row
      v-col.pa-0(
        cols=7
      )
        v-img(
          src='//source.unsplash.com/random'
          height='100vh'
        )
      v-col(
        cols=5
      )
        v-container(
          fluid
        )
          router-view
          v-row(
            justify='center'
            align='center'
          )
            v-col(
              cols='auto'
            )
              AppCopyright
</template>